services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/triton0:/triton:rw
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8080:8000"
      - "8081:8001"
      - "8082:8002"