services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    devices:
     - /dev/neuron0:/dev/neuron0
     - /dev/neuron1:/dev/neuron1
     - /dev/neuron2:/dev/neuron2
     - /dev/neuron3:/dev/neuron3
    shm_size: 16Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/triton0:/triton:rw
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"

  server_1:
    image: ${IMAGE}
    command: ${COMMAND}
    devices:
     - /dev/neuron4:/dev/neuron4
     - /dev/neuron5:/dev/neuron5
     - /dev/neuron6:/dev/neuron6
     - /dev/neuron7:/dev/neuron7
    shm_size: 16Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/triton1:/triton:rw
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8010:8000"
      - "8011:8001"
      - "8012:8002"

  server_2:
    image: ${IMAGE}
    command: ${COMMAND}
    devices:
     - /dev/neuron8:/dev/neuron8
     - /dev/neuron9:/dev/neuron9
     - /dev/neuron10:/dev/neuron10
     - /dev/neuron11:/dev/neuron11
    shm_size: 16Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/triton2:/triton:rw
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8020:8000"
      - "8021:8001"
      - "8022:8002"

  server_3:
    image: ${IMAGE}
    command: ${COMMAND}
    devices:
     - /dev/neuron12:/dev/neuron12
     - /dev/neuron13:/dev/neuron13
     - /dev/neuron14:/dev/neuron14
     - /dev/neuron15:/dev/neuron15
    shm_size: 16Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/triton3:/triton:rw
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8030:8000"
      - "8031:8001"
      - "8032:8002"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server_0
      - server_1
      - server_2
      - server_3