services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/djl-lmi:/scripts:ro
      - ${HOME}/djl-lmi:/djl-lmi:rw
      - ${HOME}/snapshots:/snapshots:rw
    ports:
      - "8080:8080"