services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - HF_MODEL_ID=${HF_MODEL_ID}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8080:8080"